spring:
  profiles:
#    active: dog,EN,prod        this is the way; but as list is also possible
     active:
       - dog
       - EN
       - prod
guru:
  username: mame
  password: 123
  jdbcurl: someUrlforDB

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl